apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vefsdvq7z-python
  janus-idp.io/tekton: vefsdvq7z-python
  backstage.io/kubernetes-id: vefsdvq7z-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vefsdvq7z-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
